In [3]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

iris = pd.read_csv('iris.data', names=['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class'])

X = iris.iloc[:, :4]
y = iris.iloc[:, 4]


iris


sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# KNN K-Fold Cross-Validation



In [4]:
for k in [1, 3, 5, 7, 9]:
  knn = KNeighborsClassifier(n_neighbors=k)
  cv_scores = cross_val_score(knn, X, y, cv=5)
  print('Usando K = {}, acurácia média de: {}%'.format(k, np.mean(cv_scores)*100))


Usando K = 1, acurácia média de: 96.0%
Usando K = 3, acurácia média de: 96.66666666666669%
Usando K = 5, acurácia média de: 97.33333333333334%
Usando K = 7, acurácia média de: 98.00000000000001%
Usando K = 9, acurácia média de: 97.33333333333334%


# KNN F-Measure

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

for k in [1, 3, 5, 7, 9]:
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  
  print('Utilizando K = {}'.format(k))
  print('Matriz de confusão: ')
  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))



Utilizando K = 1
Matriz de confusão: 
[[ 5  0  0]
 [ 0  6  1]
 [ 0  1 17]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         5
Iris-versicolor       0.86      0.86      0.86         7
 Iris-virginica       0.94      0.94      0.94        18

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30

Utilizando K = 3
Matriz de confusão: 
[[ 5  0  0]
 [ 0  6  1]
 [ 0  1 17]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         5
Iris-versicolor       0.86      0.86      0.86         7
 Iris-virginica       0.94      0.94      0.94        18

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30

Utilizando K = 5
Matriz de confusão: 
[[ 5  0 